ALTER TABLE users ADD COLUMN IF NOT EXISTS signup_source VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS signup_medium VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS signup_campaign VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS signup_referrer VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS signup_landing_path VARCHAR(255)
